#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    # Clean up nftables rules
    nft delete table inet afw 2>/dev/null || true
    systemctl daemon-reload || true
fi

#DEBHELPER#
